version: "3"

# Definição dos services
services:

# Back-end service
  back:
    image: appcriptoback
    environment:
      - MYSQL_HOST=mysqlbd
    ports:
      - "4000:4000"
    depends_on:
      - mysqlbd

# Banco Service (Mysql)
  mysqlbd:
    image: bd
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    volumes:
      - db-data:/var/lib/mysql  
# Front-end service
  front:
    image: appcriptouifront
    ports:
      - "8080:80"
    depends_on:
      - back

  
# Volumes
volumes:
  db-data:

# Newtworks para facilitar a comunicação
networks:
  backend:
  frontend:    